name: cppcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get_cppcheck
      run: sudo apt-get -y install cppcheck
    - name: Code quality
      run: make - 3_Implementation
